# Generated by Django 3.2.3 on 2021-12-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211211_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('TW', 'Top Wear'), ('BW', 'Buttom Wear')], max_length=2),
        ),
    ]
